// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy492KzEvcWtA5UNCDDx93MMSiLGa1Mqk',
    appId: '1:395158044659:web:6893be139ef272bd909c86',
    messagingSenderId: '395158044659',
    projectId: 'registration-94f2f',
    authDomain: 'registration-94f2f.firebaseapp.com',
    storageBucket: 'registration-94f2f.firebasestorage.app',
    measurementId: 'G-GWZHDQ9CYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZuBiije1qxHQ3EgKomIpk4h34jlrlQk',
    appId: '1:395158044659:android:77bbcc7a1d7a8a79909c86',
    messagingSenderId: '395158044659',
    projectId: 'registration-94f2f',
    storageBucket: 'registration-94f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHU32eFMlDytIdOrynqWP46aKQyXf3KU',
    appId: '1:395158044659:ios:b7e9bad8f312955f909c86',
    messagingSenderId: '395158044659',
    projectId: 'registration-94f2f',
    storageBucket: 'registration-94f2f.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHU32eFMlDytIdOrynqWP46aKQyXf3KU',
    appId: '1:395158044659:ios:b7e9bad8f312955f909c86',
    messagingSenderId: '395158044659',
    projectId: 'registration-94f2f',
    storageBucket: 'registration-94f2f.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy492KzEvcWtA5UNCDDx93MMSiLGa1Mqk',
    appId: '1:395158044659:web:69ba8b0e89fe43f7909c86',
    messagingSenderId: '395158044659',
    projectId: 'registration-94f2f',
    authDomain: 'registration-94f2f.firebaseapp.com',
    storageBucket: 'registration-94f2f.firebasestorage.app',
    measurementId: 'G-KF3630EWRP',
  );
}
